### PR TITLE
Transfer images

### PR DESCRIPTION
**Pull request by alexfoias**
For the moment I put the logos in a designated folder.
Not sure how to categorize the remaining images.

### CODE REVIEW

**Comment by alexfoias** [comment]
Once we decide what structure we want to keep, I'll update the paths under https://github.com/ivadomed/ivadomed

**Comment by jcohenadad** [comment]
> Once we decide what structure we want to keep, I'll update the paths under https://github.com/ivadomed/ivadomed

could you please organize the data as per the ivadomed RTD sections? e.g. 
- images [here](https://ivadomed.org/en/latest/scripts.html) go under `scripts/`
- images [here](https://ivadomed.org/en/latest/tutorials/one_class_segmentation_2d_unet.html) go under `tutorials/one_class_segmentation_2d_unet`
etc.
thanks!

**Comment by alexfoias** [comment]
I rearranged the images. Can we go ahead and merge so that I can change the main repo ? thanks

**Comment by alexfoias** [comment]
@jcohenadad I rearranged the images. Can we please go ahead and merge so that I can change the main repo ? thanks

**Review by lrouhier — COMMENTED** [review]
@alexfoias could you please change the "contribuitors" folder to 'contributors' ?(typo in the name )

**Comment by alexfoias** [comment]
@lrouhier done in 0fb5da8

**Review by lrouhier — APPROVED** [review]
Thank you very much! 👍

**Comment by alexfoias** [comment]
@jcohenadad can I merge ?

**Pull request merged**
